#!/usr/bin/env bash
# Deploy WalletDoctorLog + WalletDoctorBadge to Monad Testnet and wire apps/web/.env.local
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS="$ROOT/packages/contracts"
WEB_ENV="$ROOT/apps/web/.env.local"
export PATH="${HOME}/.foundry/bin:${PATH}"

if [[ ! -f "$CONTRACTS/.env" ]]; then
  echo "Missing packages/contracts/.env — copy from .env.example and set PRIVATE_KEY"
  exit 1
fi

# shellcheck disable=SC1091
set -a
source "$CONTRACTS/.env"
set +a

if [[ -z "${PRIVATE_KEY:-}" ]]; then
  echo "PRIVATE_KEY not set in packages/contracts/.env"
  exit 1
fi

RPC="${MONAD_TESTNET_RPC_URL:-https://testnet-rpc.monad.xyz}"
DEPLOYER=$(cast wallet address "$PRIVATE_KEY")
BAL=$(cast balance "$DEPLOYER" --rpc-url "$RPC" || echo 0)
echo "Deployer: $DEPLOYER"
echo "Balance:  $BAL wei"
echo "RPC:      $RPC"

if [[ "$BAL" == "0" ]]; then
  echo ""
  echo "⚠️  Deployer has 0 MON on testnet."
  echo "    Fund this address from the faucet, then re-run:"
  echo "      $DEPLOYER"
  echo "    Faucet: https://faucet.monad.xyz/  (or community faucets)"
  echo "    Explorer: https://testnet.monadexplorer.com/address/$DEPLOYER"
  exit 2
fi

echo "Building contracts..."
cd "$CONTRACTS"
forge build

echo "Broadcasting Deploy.s.sol..."
OUT=$(forge script script/Deploy.s.sol \
  --rpc-url "$RPC" \
  --broadcast \
  -vvv 2>&1)
echo "$OUT"

# Parse addresses from forge console2.log lines
LOG_ADDR=$(echo "$OUT" | rg -o 'WalletDoctorLog:\s*(0x[a-fA-F0-9]{40})' -r '$1' | tail -1)
BADGE_ADDR=$(echo "$OUT" | rg -o 'WalletDoctorBadge:\s*(0x[a-fA-F0-9]{40})' -r '$1' | tail -1)

# Fallback: parse latest broadcast JSON
if [[ -z "${LOG_ADDR:-}" || -z "${BADGE_ADDR:-}" ]]; then
  BROADCAST=$(ls -t "$CONTRACTS/broadcast/Deploy.s.sol/10143/run-"*.json 2>/dev/null | head -1 || true)
  if [[ -n "${BROADCAST:-}" ]]; then
    LOG_ADDR=$(python3 - << PY
import json
d=json.load(open("$BROADCAST"))
txs=d.get("transactions") or []
# first create is Log, second is Badge (constructor arg = log)
for t in txs:
    if t.get("contractName")=="WalletDoctorLog":
        print(t.get("contractAddress") or t.get("additionalContracts",[{}])[0].get("address",""))
        break
else:
    # try returns / deployments
    for t in txs:
        ca=t.get("contractAddress")
        if ca: 
            print(ca); break
PY
)
    BADGE_ADDR=$(python3 - << PY
import json
d=json.load(open("$BROADCAST"))
txs=d.get("transactions") or []
found=False
for t in txs:
    name=t.get("contractName") or ""
    ca=t.get("contractAddress")
    if name=="WalletDoctorBadge" and ca:
        print(ca); found=True; break
if not found:
    creates=[t.get("contractAddress") for t in txs if t.get("contractAddress")]
    if len(creates)>=2: print(creates[1])
PY
)
  fi
fi

if [[ -z "${LOG_ADDR:-}" || -z "${BADGE_ADDR:-}" ]]; then
  echo "Could not parse deploy addresses from forge output. Check broadcast/ folder."
  exit 1
fi

echo ""
echo "✅ Deployed"
echo "  WalletDoctorLog:   $LOG_ADDR"
echo "  WalletDoctorBadge: $BADGE_ADDR"
echo "  Explorer log:   https://testnet.monadexplorer.com/address/$LOG_ADDR"
echo "  Explorer badge: https://testnet.monadexplorer.com/address/$BADGE_ADDR"

# Wire web env
mkdir -p "$(dirname "$WEB_ENV")"
if [[ -f "$WEB_ENV" ]]; then
  # upsert keys
  python3 - << PY
from pathlib import Path
path = Path("$WEB_ENV")
text = path.read_text() if path.exists() else ""
updates = {
    "NEXT_PUBLIC_LOG_ADDRESS_TESTNET": "$LOG_ADDR",
    "NEXT_PUBLIC_BADGE_ADDRESS_TESTNET": "$BADGE_ADDR",
    "NEXT_PUBLIC_MONAD_TESTNET_RPC": "$RPC",
}
lines = text.splitlines()
keys_done = set()
out = []
for line in lines:
    if "=" in line and not line.strip().startswith("#"):
        k = line.split("=",1)[0].strip()
        if k in updates:
            out.append(f"{k}={updates[k]}")
            keys_done.add(k)
            continue
    out.append(line)
for k,v in updates.items():
    if k not in keys_done:
        out.append(f"{k}={v}")
path.write_text("\n".join(out) + "\n")
print("Updated", path)
PY
else
  cat > "$WEB_ENV" << EOF
# Generated by scripts/deploy-testnet.sh
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=
NEXT_PUBLIC_MONAD_TESTNET_RPC=${RPC}
NEXT_PUBLIC_MONAD_MAINNET_RPC=https://rpc.monad.xyz
NEXT_PUBLIC_LOG_ADDRESS_TESTNET=${LOG_ADDR}
NEXT_PUBLIC_BADGE_ADDRESS_TESTNET=${BADGE_ADDR}
NEXT_PUBLIC_LOG_ADDRESS_MAINNET=0x0000000000000000000000000000000000000000
NEXT_PUBLIC_BADGE_ADDRESS_MAINNET=0x0000000000000000000000000000000000000000
NEXT_PUBLIC_SCAN_LOOKBACK_BLOCKS=50000
NEXT_PUBLIC_SCAN_CHUNK_SIZE=2000
EOF
  echo "Created $WEB_ENV"
fi

# Also write deployments.json for reference
cat > "$CONTRACTS/deployments.testnet.json" << EOF
{
  "chainId": 10143,
  "network": "monad-testnet",
  "deployer": "$DEPLOYER",
  "WalletDoctorLog": "$LOG_ADDR",
  "WalletDoctorBadge": "$BADGE_ADDR",
  "rpc": "$RPC",
  "explorer": {
    "log": "https://testnet.monadexplorer.com/address/$LOG_ADDR",
    "badge": "https://testnet.monadexplorer.com/address/$BADGE_ADDR"
  }
}
EOF

echo ""
echo "Next:"
echo "  1) Set NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID in apps/web/.env.local"
echo "     → https://cloud.walletconnect.com"
echo "  2) pnpm dev"
echo "  3) Connect wallet on Monad Testnet and scan/revoke"
