#!/usr/bin/env bash
# Deploy contracts to Monad Testnet and wire apps/web/.env.local (Log address for the product)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONTRACTS="$ROOT/packages/contracts"
WEB_ENV="$ROOT/apps/web/.env.local"
export PATH="${HOME}/.foundry/bin:${PATH}"

if [[ ! -f "$CONTRACTS/.env" ]]; then
  echo "Missing packages/contracts/.env — copy from .env.example and set PRIVATE_KEY"
  exit 1
fi

# shellcheck disable=SC1091
set -a
source "$CONTRACTS/.env"
set +a

if [[ -z "${PRIVATE_KEY:-}" ]]; then
  echo "PRIVATE_KEY not set in packages/contracts/.env"
  exit 1
fi

RPC="${MONAD_TESTNET_RPC_URL:-https://testnet-rpc.monad.xyz}"
DEPLOYER=$(cast wallet address "$PRIVATE_KEY")
BAL=$(cast balance "$DEPLOYER" --rpc-url "$RPC" || echo 0)
echo "Deployer: $DEPLOYER"
echo "Balance:  $BAL wei"
echo "RPC:      $RPC"

if [[ "$BAL" == "0" ]]; then
  echo ""
  echo "⚠️  Deployer has 0 MON on testnet."
  echo "    Fund this address from the faucet, then re-run:"
  echo "      $DEPLOYER"
  echo "    Faucet: https://faucet.monad.xyz/  (or community faucets)"
  echo "    Explorer: https://testnet.monadexplorer.com/address/$DEPLOYER"
  exit 2
fi

echo "Building contracts..."
cd "$CONTRACTS"
forge build

echo "Broadcasting Deploy.s.sol..."
OUT=$(forge script script/Deploy.s.sol \
  --rpc-url "$RPC" \
  --broadcast \
  -vvv 2>&1)
echo "$OUT"

# Parse addresses from forge console2.log lines
LOG_ADDR=$(echo "$OUT" | rg -o 'WalletDoctorLog:\s*(0x[a-fA-F0-9]{40})' -r '$1' | tail -1)
BADGE_ADDR=$(echo "$OUT" | rg -o 'WalletDoctorBadge:\s*(0x[a-fA-F0-9]{40})' -r '$1' | tail -1)

# Fallback: parse latest broadcast JSON (Log is required; Badge optional/legacy)
if [[ -z "${LOG_ADDR:-}" ]]; then
  BROADCAST=$(ls -t "$CONTRACTS/broadcast/Deploy.s.sol/10143/run-"*.json 2>/dev/null | head -1 || true)
  if [[ -n "${BROADCAST:-}" ]]; then
    LOG_ADDR=$(python3 - << PY
import json
d=json.load(open("$BROADCAST"))
txs=d.get("transactions") or []
for t in txs:
    if t.get("contractName")=="WalletDoctorLog":
        print(t.get("contractAddress") or "")
        break
else:
    for t in txs:
        ca=t.get("contractAddress")
        if ca:
            print(ca); break
PY
)
    if [[ -z "${BADGE_ADDR:-}" ]]; then
      BADGE_ADDR=$(python3 - << PY
import json
d=json.load(open("$BROADCAST"))
txs=d.get("transactions") or []
for t in txs:
    if (t.get("contractName") or "")=="WalletDoctorBadge" and t.get("contractAddress"):
        print(t.get("contractAddress")); break
PY
)
    fi
  fi
fi

if [[ -z "${LOG_ADDR:-}" ]]; then
  echo "Could not parse WalletDoctorLog address from forge output. Check broadcast/ folder."
  exit 1
fi

echo ""
echo "✅ Deployed"
echo "  WalletDoctorLog:   $LOG_ADDR"
echo "  Explorer log:   https://testnet.monadexplorer.com/address/$LOG_ADDR"
if [[ -n "${BADGE_ADDR:-}" ]]; then
  echo "  (legacy WalletDoctorBadge still in Deploy.s.sol: $BADGE_ADDR — not used by the web app)"
fi

# Wire web env (product uses Log only)
mkdir -p "$(dirname "$WEB_ENV")"
if [[ -f "$WEB_ENV" ]]; then
  # upsert keys
  python3 - << PY
from pathlib import Path
path = Path("$WEB_ENV")
text = path.read_text() if path.exists() else ""
# Do NOT overwrite NEXT_PUBLIC_MONAD_*_RPC — user may use Alchemy / premium RPC
updates = {
    "NEXT_PUBLIC_LOG_ADDRESS_TESTNET": "$LOG_ADDR",
}
# Drop obsolete badge env keys if present
drop = {"NEXT_PUBLIC_BADGE_ADDRESS_TESTNET", "NEXT_PUBLIC_BADGE_ADDRESS_MAINNET"}
lines = text.splitlines()
keys_done = set()
out = []
for line in lines:
    if "=" in line and not line.strip().startswith("#"):
        k = line.split("=",1)[0].strip()
        if k in drop:
            continue
        if k in updates:
            out.append(f"{k}={updates[k]}")
            keys_done.add(k)
            continue
    out.append(line)
for k,v in updates.items():
    if k not in keys_done:
        out.append(f"{k}={v}")
path.write_text("\n".join(out) + "\n")
print("Updated", path)
PY
else
  cat > "$WEB_ENV" << EOF
# Generated by scripts/deploy-testnet.sh
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=
NEXT_PUBLIC_MONAD_TESTNET_RPC=${RPC}
NEXT_PUBLIC_MONAD_MAINNET_RPC=https://rpc.monad.xyz
NEXT_PUBLIC_LOG_ADDRESS_TESTNET=${LOG_ADDR}
NEXT_PUBLIC_LOG_ADDRESS_MAINNET=0x0000000000000000000000000000000000000000
NEXT_PUBLIC_USE_HYPERSYNC=true
NEXT_PUBLIC_SCAN_CHUNK_SIZE=100
NEXT_PUBLIC_SCAN_MIN_CHUNK=50
NEXT_PUBLIC_SCAN_CONCURRENCY=8
EOF
  echo "Created $WEB_ENV"
fi

# Also write deployments.json for reference
cat > "$CONTRACTS/deployments.testnet.json" << EOF
{
  "chainId": 10143,
  "network": "monad-testnet",
  "deployer": "$DEPLOYER",
  "WalletDoctorLog": "$LOG_ADDR",
  "rpc": "$RPC",
  "version": 3,
  "features": {
    "batchLogCleanup": true,
    "maxBatch": 25
  },
  "explorer": {
    "log": "https://testnet.monadexplorer.com/address/$LOG_ADDR"
  },
  "notes": {
    "product": "Web app uses WalletDoctorLog only (scan / revoke / log + score)."
  }
}
EOF

echo ""
echo "Next:"
echo "  1) Set NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID in apps/web/.env.local"
echo "     → https://cloud.walletconnect.com"
echo "  2) pnpm dev"
echo "  3) Connect wallet on Monad Testnet and scan/revoke"
